branches:
  only:
    - /^Development-.*$/
    - /^Minecraft-.*$/
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -i -S
after_success:
  - ./gradlew uploadJars -S
  - ./gradlew curseforge -S
  - ./gradlew createGithubBranches -S
